// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mycloud-mobile/App.tsx": () => import("../components/mockups/mycloud-mobile/App.tsx"),
  "./components/mockups/mycloud-web/Desktop.tsx": () => import("../components/mockups/mycloud-web/Desktop.tsx")
};
